name: gift_grab
description: Game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.0.9+9

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.1.8
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.0
  flame: ^1.4.0
  flame_audio: ^2.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^14.1.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1 
  nakama: ^1.1.0
  path_provider: ^2.1.3 
  toggle_switch: ^2.0.1
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
