name: gift_grab
description: Game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.0.8+8

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flame_audio: ^2.0.5
  hive: ^2.2.3
  nakama: ^1.0.0
  path_provider: ^2.0.11
  platform_device_id: ^1.0.1
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
